src/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'doctors', views.DoctorViewSet)
router.register(r'specialities', views.SpecialityViewSet)
router.register(r'timetables', views.TimetableViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^times/(?P<doctor_id>[0-9]+)/(?P<day>\d{4}\-\d{2}\-\d{2})/$', views.get_times, name='get-times'),
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
]

src/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('front.urls', namespace='front')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls', namespace='api'))
]

src/front/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^details/(?P<pk>\d+)/$', views.details, name='details'),
]

src/appointment/models.py
from django.db import models


class Appointment(models.Model):
    first_name = models.CharField(max_length=128, blank=False, null=False)
    last_name = models.CharField(max_length=128, blank=False, null=False)
    appointment_day = models.DateField(blank=False, null=False)
    start_time = models.TimeField(blank=False, null=False)
    end_time = models.TimeField(blank=False, null=False)
    doctor = models.ForeignKey('clinic.Doctor', on_delete=models.CASCADE)

    def __str__(self):
        return '%s %s :: %s' % (self.first_name, self.last_name, self.doctor)

    class Meta:
        index_together = [
            ['first_name', 'last_name']
        ]
        unique_together = [
            ['doctor', 'appointment_day', 'start_time', 'end_time']
        ]

src/clinic/models.py
from django.db import models


class Speciality(models.Model):
    title = models.CharField(max_length=128, blank=False, null=False, unique=True)
    sorder = models.IntegerField(blank=True, null=False, default=0, db_index=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['sorder']


class Doctor(models.Model):
    first_name = models.CharField(max_length=128, blank=False, null=False)
    last_name = models.CharField(max_length=128, blank=False, null=False)
    sorder = models.IntegerField(blank=True, null=False, default=0, db_index=True)
    speciality = models.ForeignKey(Speciality, on_delete=models.PROTECT)

    def __str__(self):
        return ' '.join([self.first_name, self.last_name])

    class Meta:
        ordering = ['sorder']
        index_together = [
            ['first_name', 'last_name']
        ]

src/timetables/models.py
from django.db import models


class Timetable(models.Model):
    DW_MON = 0
    DW_TUE = 1
    DW_WED = 2
    DW_THU = 3
    DW_FRI = 4

    DAY_OF_WEEK_CHOICES = (
        (DW_MON, 'Monday'),
        (DW_TUE, 'Tuesday'),
        (DW_WED, 'Wednesday'),
        (DW_THU, 'Thursday'),
        (DW_FRI, 'Friday'),
    )

    day_of_week = models.IntegerField(choices=DAY_OF_WEEK_CHOICES, null=False, blank=False)
    start_time = models.TimeField(null=False, blank=False)
    end_time = models.TimeField(null=False, blank=False)
    break_start_time = models.TimeField(null=False, blank=False)
    break_end_time = models.TimeField(null=False, blank=False)
    doctor = models.ForeignKey('clinic.Doctor', on_delete=models.CASCADE)

    def __str__(self):
        return 'Timetable for "%s" %s %s-%s (%s-%s)' % (
            str(self.doctor),
            dict(Timetable.DAY_OF_WEEK_CHOICES)[self.day_of_week],
            self.start_time,
            self.end_time,
            self.break_start_time,
            self.break_end_time,
        )

    class Meta:
        unique_together = [
            ['doctor', 'day_of_week'],
        ]

src/front/forms.py
from django import forms


class AppointmentForm(forms.Form):
    speciality = forms.IntegerField()
    doctor = forms.IntegerField(required=True)
    day = forms.DateField(required=True)
    time = forms.TimeField(required=True)
    first_name = forms.CharField(required=True, max_length=128)
    last_name = forms.CharField(required=True, max_length=128)

src/api/views.py
import datetime
from rest_framework import viewsets, status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django_filters.rest_framework import DjangoFilterBackend

from appointment.models import Appointment
from clinic.models import Doctor, Speciality
from timetables.models import Timetable
from .serializers import AppointmentSerializer, DoctorSerializer, SpecialitySerializer, TimetableSerializer


@api_view(['GET', 'HEAD'])
def get_times(request, doctor_id, day, format=None):
    try:
        doctor = Doctor.objects.get(pk=doctor_id)
    except Doctor.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    dt = datetime.datetime.strptime(day, '%Y-%m-%d')
    weekday = dt.weekday()

    try:
        timetable = doctor.timetable_set.get(day_of_week=weekday)
    except Timetable.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    appointments = doctor.appointment_set.filter(appointment_day=day)
    busy_hours = [app.start_time.hour for app in appointments]
    busy_hours.append(timetable.break_start_time.hour)

    hours = [datetime.time(hour=h, minute=timetable.start_time.minute).strftime('%H:%M') for h in range(timetable.start_time.hour, timetable.end_time.hour) if h not in busy_hours]

    return Response(hours)


class DoctorViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Doctor.objects.all()
    serializer_class = DoctorSerializer
    filter_backends = (DjangoFilterBackend,)
    filter_fields = ('speciality',)


class SpecialityViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Speciality.objects.all()
    serializer_class = SpecialitySerializer


class TimetableViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Timetable.objects.all()
    serializer_class = TimetableSerializer
    filter_backends = (DjangoFilterBackend,)
    filter_fields = ('doctor', 'day_of_week')

src/appointment/views.py
from django.shortcuts import render

# Create your views here.

src/clinic/views.py
from django.shortcuts import render

# Create your views here.

src/front/views.py
import datetime

from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect

from .forms import AppointmentForm
from appointment.models import Appointment


def index(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)

        if form.is_valid():
            start_time = datetime.datetime.strptime(form.data['time'], '%H:%M')
            end_time = start_time + datetime.timedelta(hours=1)

            appointment = Appointment()
            appointment.doctor_id = form.data['doctor']
            appointment.appointment_day = form.data['day']
            appointment.start_time = start_time.strftime('%H:%M')
            appointment.end_time = end_time.strftime('%H:%M')
            appointment.first_name = form.data['first_name']
            appointment.last_name = form.data['last_name']
            appointment.save()

            return HttpResponseRedirect(reverse('front:details', args=[appointment.id]))
    else:
        form = AppointmentForm()

    return render(request, 'front/index.html', {'form': form})


def details(request, pk):
    appointment = get_object_or_404(Appointment, pk=pk)

    return render(request, 'front/details.html', {
        'appointment': appointment,
    })

src/timetables/views.py
from django.shortcuts import render

# Create your views here.

src/front/templates/front/details.html
{% extends 'front/layout.html' %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Талон #{{ appointment.id }}</h4>
            <table class="table">
                <tr>
                    <th>Дата</th>
                    <td>{{ appointment.appointment_day|date }}</td>
                </tr>
                <tr>
                    <th>Время</th>
                    <td>{{ appointment.start_time|time }}</td>
                </tr>
                <tr>
                    <th>Специалист</th>
                    <td>{{ appointment.doctor.speciality.title }}</td>
                </tr>
                <tr>
                    <th>Врач</th>
                    <td>{{ appointment.doctor }}</td>
                </tr>
                <tr>
                    <th>Пациент</th>
                    <td>{{ appointment.first_name}} {{ appointment.last_name }}</td>
                </tr>
            </table>

            <button class="btn btn-primary" onclick="window.print()">Распечатать</button>
        </div>
    </div>
{% endblock %}

src/front/templates/front/index.html
{% extends 'front/layout.html' %}

{% load static %}

{% block header %}

    <h1>Запись на прием</h1>

{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}

        <div class="form-group">
            <label for="{{ form.speciality.id_for_label }}">Специалист</label>
            <select
                name="{{ form.speciality.html_name }}"
                id="{{ form.speciality.id_for_label }}"
                class="form-control fld-speciality"
                disabled
                data-url="{% url 'api:speciality-list' %}">
            </select>
        </div>

        <div class="form-group">
            <label for="{{ form.doctor.id_for_label }}">Врач</label>
            <select
                name="{{ form.doctor.html_name }}"
                id="{{ form.doctor.id_for_label }}"
                class="form-control"
                disabled
                data-url="{% url 'api:doctor-list' %}">
            </select>
        </div>

        <div class="form-group">
            <label for="{{ form.day.id_for_label }}">День записи</label>
            <div id="{{ form.day.id_for_label }}-datepicker" data-date="01/08/2017"></div>
            <input
                type="hidden"
                name="{{ form.day.html_name }}"
                id="{{ form.day.id_for_label }}"
                data-url="{% url 'api:timetable-list' %}"
            >
        </div>

        <div class="form-group">
            <label for="{{ form.time.id_for_label }}">Время приема</label>
            <select
                name="{{ form.time.html_name }}"
                id="{{ form.time.id_for_label }}"
                class="form-control"
                disabled
                data-base-url="/api/times">
            </select>
        </div>
        
        <div class="form-group">
            <label for="{{ form.first_name.id_for_label }}">Имя</label>
            <input
                name="{{ form.first_name.html_name }}"
                id="{{ form.first_name.id_for_label }}"
                class="form-control"
            >
        </div>

        <div class="form-group">
            <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
            <input
                name="{{ form.last_name.html_name }}"
                id="{{ form.last_name.id_for_label }}"
                class="form-control"
            >
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Записаться" />
        </div>
    </form>
{% endblock %}

{% block body_scripts %}

    {{ block.super }}

    <script src="{% static 'front/js/index.js' %}"></script>
{% endblock %}

src/front/templates/front/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker3.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'front/css/layout.css' %}">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'front:index' %}">
            <i class="fa fa-medkit text-danger"></i>
            Записаться к врачу
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/memclutter/clinic-crm"><i class="fa fa-github"></i> GitHub</a>
                </li>
                {% if request.user.is_staff %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarSupportedContent" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-dashboard"></i> Администрирование
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarSupportedContent">
                            <a class="dropdown-item" href="{% url 'admin:clinic_speciality_changelist' %}">Специалисты</a>
                            <a class="dropdown-item" href="{% url 'admin:clinic_doctor_changelist' %}">Врачи</a>
                            <a class="dropdown-item" href="{% url 'admin:timetables_timetable_changelist' %}">График работы</a>
                            <a class="dropdown-item" href="{% url 'admin:appointment_appointment_changelist' %}">Записи к врачам</a>
                        </div>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container content-wrapper">
        <div class="row">
            <div class="col">
                {% block header %}{% endblock %}
            </div>
        </div>

        <div class="row">
            <div class="col">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>

    {% block body_scripts %}
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/locales/bootstrap-datepicker.ru.min.js"></script>
    {% endblock %}
</body>
</html>